version: '3'

services:

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  web:
    links:
      - postgres:postgres
      - redis:redis
    image: cnachteg/alambic:0.1
    volumes:
      - .:/app
      - ~/data_alambic:/app/data_alambic
    command: bash entrypoint.sh
    env_file:
      - ./.env.dev
    ports:
      - "8000:8000"

  celery:
    restart: always
    links:
      - postgres:postgres
      - redis:redis
    image: cnachteg/alambic:0.1
    command: celery -A alambic worker -l info
    volumes:
      - .:/app
      - ~/data_alambic:/app/data_alambic
    env_file:
      - ./.env.dev
    depends_on:
      - postgres
      - redis
      - web

volumes:
  pgdata:
  redisdata: