# Generated by Django 2.2 on 2021-12-03 18:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('alambic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={},
        ),
        migrations.AlterModelOptions(
            name='label',
            options={},
        ),
        migrations.AlterField(
            model_name='image',
            name='content',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None),
                size=None), size=None),
        ),
    ]
