# Generated by Django 4.0 on 2022-02-10 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('alambic_app', '0004_alter_result_cross_val'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.BigIntegerField()),
                ('end', models.BigIntegerField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EntitytoRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alambic_app.entity')),
            ],
        ),
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('color', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('components', models.ManyToManyField(through='alambic_app.EntitytoRelation', to='alambic_app.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='RelationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('color', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='RelationLabel',
            fields=[
                ('label_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='alambic_app.label')),
                ('relations', models.ManyToManyField(to='alambic_app.Relation')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('alambic_app.label',),
        ),
        migrations.AddField(
            model_name='relation',
            name='relation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alambic_app.relationtype'),
        ),
        migrations.AddField(
            model_name='entitytorelation',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alambic_app.relation'),
        ),
        migrations.AddField(
            model_name='entity',
            name='entity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alambic_app.entitytype'),
        ),
        migrations.AlterUniqueTogether(
            name='entitytorelation',
            unique_together={('entity', 'relation')},
        ),
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together={('start', 'end', 'entity_type', 'content')},
        ),
    ]
