# Generated by Django 4.0 on 2022-02-14 15:37

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('alambic_app', '0005_entity_entitytorelation_entitytype_relation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitytype',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='relationtype',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
    ]
