# Generated by Django 4.0 on 2023-06-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alambic_app', '0008_result_cross_val_result_repeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='misc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='filename',
            field=models.TextField(blank=True),
        ),
    ]
