remote_theme: just-the-docs/just-the-docs
ga_tracking: G-94CDFXRBRT
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true by default)


color_scheme: alambic
logo: "assets/images/alambic_title.png"

title: ALAMBIC
description: Active Learning Automation with Methods to Battle Insufficient Curation

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright 2022 Charlotte Nachtegael"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

gh_edit_link: false

compress_html:
  ignore:
    envs: all